<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["user/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["user/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Uid</th>
            <th>Mobile</th>
            <th>Partner</th>
            <th>Password</th>
            <th>User Of Name</th>
            <th>Jname</th>
            <th>Web Of Mode</th>
            <th>Account Of Status</th>
            <th>Score</th>
            <th>Invite Of User</th>
            <th>Is Of Give Of Invite Of User Of Score</th>
            <th>Status</th>
            <th>Login Of Time</th>
            <th>Create Of Time</th>
            <th>Update Of Time</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $user): ?>
            <tr>
                <td><?php echo $user->uid ?></td>
            <td><?php echo $user->mobile ?></td>
            <td><?php echo $user->partner ?></td>
            <td><?php echo $user->password ?></td>
            <td><?php echo $user->user_name ?></td>
            <td><?php echo $user->jname ?></td>
            <td><?php echo $user->web_mode ?></td>
            <td><?php echo $user->account_status ?></td>
            <td><?php echo $user->score ?></td>
            <td><?php echo $user->invite_user_id ?></td>
            <td><?php echo $user->is_give_invite_user_score ?></td>
            <td><?php echo $user->status ?></td>
            <td><?php echo $user->login_time ?></td>
            <td><?php echo $user->create_time ?></td>
            <td><?php echo $user->update_time ?></td>

                <td><?php echo $this->tag->linkTo(["user/edit/" . $user->uid, "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["user/delete/" . $user->uid, "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("user/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("user/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
